# DB config
spring:
  datasource:
    url: ${MY_DATASOURCE_URL:jdbc:mysql://localhost:3306/mcp_server_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# MCP server config
  ai:
    mcp:
      server:
        name: stdio-mcp-server
        version: 0.0.1 # provide the versioning according to me
        stdio: true # register it a stdio type
  main:
    web-application-type: none # not a web app
    banner-mode: off # important for stdio
  config:
    import: file:.env[.properties]

# Keep logs clean (important for stdio)
logging:
  file:
    name: ./logs/mcp-server.log # log file will be created automatically
  level:
    root: OFF # disable console logging for stdio apps