spring:
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: ${AI_CHAT_MODEL}
          temperature: 0.7
          max-tokens: 1000
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
  config:
    import: file:.env[.properties]
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
