spring:
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    vectorstore:
      mariadb:
        initialize-schema: true
        distance-type: COSINE
        dimensions: ${DIMENSIONS}
        table-name: embeddings_table
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: ${AI_CHAT_MODEL}
          temperature: 0.7
          max-tokens: 1000

  datasource:
    url: jdbc:mariadb://localhost:3307/test_DB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  config:
    import: file:.env[.properties]

weather:
  api:
    key: ${WEATHER_API_KEY}

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
